version: "3.1"

services:
    dob-nginx-php:
        image: 777383/nginx-php-image:0.1
        deploy:
          replicas: 3
        ports:
            - 8080:80
        volumes:
            - "/web:/var/www/html:ro"
        networks:
            - dob-network
        depends_on:
            - dob-mysql

    dob-mysql:
        image: mysql:8.0
        deploy:
          replicas: 1
        ports:
            - 3306:3306
        volumes:
            - "/db:/docker-entrypoint-initdb.d:ro"
        networks:
            - dob-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
        command: --default-authentication-plugin=mysql_native_password
        restart: always

networks:
    dob-network:
